In [16]:
import numpy as np
arr = np.array([[1,2,3,4],
                [5,6,7,8],
                [5,6,7,8],
                [5,6,7,8],
                [5,6,7,8]])
len(arr)

5

In [19]:
np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [25]:
d = np.arange(1,2,3)
print(d)

[1]


In [27]:
np.linspace(0,8,7)

array([0.        , 1.33333333, 2.66666667, 4.        , 5.33333333,
       6.66666667, 8.        ])

In [35]:
e = np.full((14),2)
print(e)
print(e.ndim)

[2 2 2 2 2 2 2 2 2 2 2 2 2 2]
1


In [39]:
e = np.full((2,2),87)
print(e)
print(e.ndim)

[[87 87]
 [87 87]]
2


In [41]:
e = np.full((2,2,2),5)
print(e)
print(e.ndim)

[[[5 5]
  [5 5]]

 [[5 5]
  [5 5]]]
3


In [43]:
f = np.eye(8)
print(f)

[[1. 0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0. 0. 0.]
 [0. 0. 0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 0. 0. 1.]]


In [45]:
np.random.random((2,5))

array([[0.02199757, 0.44579027, 0.40549329, 0.91268258, 0.4871707 ],
       [0.48517331, 0.2408907 , 0.97293419, 0.95744314, 0.14146499]])

In [47]:
np.random.randint((2,3))

array([0, 0])

In [51]:
# to find shape of an array
arr = np.array([[1,2,3,4],
                [5,6,7,8]])

print(arr.shape)

# output explanation


(2, 4)


In [55]:
# to find no of elements in array
arr = np.array([[1,2,3,4],
                [5,6,7,8],
                [5,6,7,8]])
print(arr.size)

12


In [59]:
# to find len of array
arr = np.array([[1,2,3,4],
                [2,3,4,5]])
len(arr)

2

In [70]:
arr = np.array([[1,2,3,4,5,6,7,8,9]])
len(arr)
               

1

In [72]:
arr = np.array([[1,2,3,4]])
print(arr.size)

4


In [80]:
arr = np.array([[1,2,3,4]])
print(arr.shape)
            

(1, 4)


In [5]:
arr =np.array([1,2,3,4])
print(arr[2])

3


In [7]:
# adding two index position
arr = np.array([1,2,3,4])
print(arr[2]+arr[3]+arr[0])

8


In [28]:
# Acess 2-D arrays
array = np.array([[1,2,3,4,5],
                  [6,7,8,9,10],
                  [6,7,8,9,10],
                  [6,7,8,9,1]])
print(arr[3,2])

7


In [60]:
# Accessing 3D arrays 
arr = np.array([[[1,2,3],[4,5,6]],
                [[1,22,3],[24,5,6]],
                [[1,32,32],[4,2,6]],
                [[7,8,9],[10,11,12]]])
print(arr[3,1,2])


12


In [62]:
# Accessing index
print(arr[1,0,1

22


In [66]:
# data types
# string
arr = np.array([1,2,3,4], dtype = "S")
print(arr)
print(arr.dtype)

[b'1' b'2' b'3' b'4']
|S1


In [71]:
# integer
arr = np.array([1,2,3,4], dtype = "i4")
print(arr)
print(arr.dtype)

[1 2 3 4]
int32


In [73]:
# change data type from float to integer by using 'i' as parameter value:
arr = np.array([1.1,2.1,3.1])
newarr = arr.astype('i')
print(newarr)
print(newarr.dtype)

[1 2 3]
int32


In [75]:
# change data type from integer to boolean:
arr = np.array([1,0,3])
newarr = arr.astype(bool)
print(newarr)
print(newarr.dtype)


[ True False  True]
bool


In [77]:
#copy method
arr = np.array([1,2,3,4,5])
x = arr.view()
arr[0] = 42
print(arr)
print(x)

[42  2  3  4  5]
[42  2  3  4  5]


In [79]:
arr = np.array([[1,2,3,4],
                [5,6,7,8]])
print(arr.shape)


(2, 4)


In [81]:
# Reshaping arrays
# convert the following 1-D array with 12 elements into 2-D array
arr = np.array([1,2,3,4,5,6,7,8,9,10,11,12])
print(arr.size)
print("+++++++++++++++++++++++")
newarr = arr.reshape(2,6)
print(newarr)

12
+++++++++++++++++++++++
[[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]]


In [83]:
# convert the following in 3-D array
arr = np.array([1,2,3,4,5,6,7,8,9,10,11,12])
newarr = arr.reshape(2,2,3)
print(newarr)

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]


In [85]:
# a data type object
x = np.array([[1,2],[3,4]], dtype = np.float64)
y = np.array([[5,6],[7,8]], dtype = np.float64)

# adding of two arrays
print(x+y)
print(np.add(x,y))


[[ 6.  8.]
 [10. 12.]]
[[ 6.  8.]
 [10. 12.]]


In [93]:
# substraction of two arrays
print(x-y)
print(np.subtract(x,y))

[[-4. -4.]
 [-4. -4.]]
[[-4. -4.]
 [-4. -4.]]


In [95]:
# multiplication of two arrays
print(x*y)

[[ 5. 12.]
 [21. 32.]]


In [97]:
# division of two arrays
print(x/y)

[[0.2        0.33333333]
 [0.42857143 0.5       ]]


In [101]:

print(x%y)

[[1. 2.]
 [3. 4.]]


In [103]:
print(x//y)

[[0. 0.]
 [0. 0.]]


In [1]:
#Try converting 1D array with 8 elements to a 2D array with 3 elements in each dimension (will raise an error):

import numpy as np

arr = np.array([1, 2, 3, 4, 5, 6, 7, 8])

newarr = arr.reshape(2,4)

print(newarr)

[[1 2 3 4]
 [5 6 7 8]]


In [120]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5, 6, 7, 8])

newarr = arr.reshape(2, 2, -1)

print(newarr)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [126]:
arr = np.array([1,2,3,4,5,6,7,8,9,10,11,12])
newarr = arr.reshape(2,6,-1)
print(newarr)

[[[ 1]
  [ 2]
  [ 3]
  [ 4]
  [ 5]
  [ 6]]

 [[ 7]
  [ 8]
  [ 9]
  [10]
  [11]
  [12]]]


In [150]:
arr = np.array([1,2,3,4,5,6,7,8,9,10,11,12,1,2,3,4,5,6,7,8,9,10,11,12])
newarr = arr.reshape(6,4,-1)
print(newarr)

[[[ 1]
  [ 2]
  [ 3]
  [ 4]]

 [[ 5]
  [ 6]
  [ 7]
  [ 8]]

 [[ 9]
  [10]
  [11]
  [12]]

 [[ 1]
  [ 2]
  [ 3]
  [ 4]]

 [[ 5]
  [ 6]
  [ 7]
  [ 8]]

 [[ 9]
  [10]
  [11]
  [12]]]


In [204]:
arr = np.array([1,2,3,4,5,6,7,8,9,10,11,12,1,2,3,4,5,6,7,8,9,10,11,12])
newarr = arr.reshape(12,2)
print(newarr)

[[ 1  2]
 [ 3  4]
 [ 5  6]
 [ 7  8]
 [ 9 10]
 [11 12]
 [ 1  2]
 [ 3  4]
 [ 5  6]
 [ 7  8]
 [ 9 10]
 [11 12]]


In [184]:
arr = np.array([1,2,3,4,5,6,7,8,9,10,11,12,1,2,3,4,5,6,7,8,9,10,11,12,1,2,3,4,5,6,7,8,9,10,11,12,1,2,3,4,5,6,7,8,9,10,11,12])
newarr = arr.reshape(6,4,2)
print(newarr)

[[[ 1  2]
  [ 3  4]
  [ 5  6]
  [ 7  8]]

 [[ 9 10]
  [11 12]
  [ 1  2]
  [ 3  4]]

 [[ 5  6]
  [ 7  8]
  [ 9 10]
  [11 12]]

 [[ 1  2]
  [ 3  4]
  [ 5  6]
  [ 7  8]]

 [[ 9 10]
  [11 12]
  [ 1  2]
  [ 3  4]]

 [[ 5  6]
  [ 7  8]
  [ 9 10]
  [11 12]]]


In [202]:
arr = np.array([1,2,3,4,5,6,7,8,9,10,11,12,1,2,3,4,5,6,7,8,9,10,11,12,1,2,3,4,5,6,7,8,9,10,11,12,1,2,3,4,5,6,7,8,9,10,11,12])
newarr = arr.reshape(6,2,4)
print(newarr)

[[[ 1  2  3  4]
  [ 5  6  7  8]]

 [[ 9 10 11 12]
  [ 1  2  3  4]]

 [[ 5  6  7  8]
  [ 9 10 11 12]]

 [[ 1  2  3  4]
  [ 5  6  7  8]]

 [[ 9 10 11 12]
  [ 1  2  3  4]]

 [[ 5  6  7  8]
  [ 9 10 11 12]]]


In [206]:
arr = np.array([1,2,3,4,5,6,7,8,9,10,11,12,1,2,3,4,5,6,7,8,9,10,11,12,1,2,3,4,5,6,7,8,9,10,11,12,1,2,3,4,5,6,7,8,9,10,11,12])
newarr = arr.reshape(12,4)
print(newarr)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [3]:
#converting 3D array into 1D array
arr=np.array([[[1,2,3,4,5,6],[7,8,9,10,11,12]],
              [[13,14,15,16,17,18],[19,20,21,22,23,24]],
              [[25,26,27,28,29,30],[31,32,33,34,35,36]]])
x=arr.reshape(arr.size)
print(x)

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24
 25 26 27 28 29 30 31 32 33 34 35 36]


In [14]:
#converting 3D array into 2D array
arr=np.array([[[1,2,3,4,5,6],[7,8,9,10,11,12]],
              [[13,14,15,16,17,18],[19,20,21,22,23,24]],
              [[25,26,27,28,29,30],[31,32,33,34,35,36]]])
print(arr.size)
x=arr.reshape(6,6)
print(x)
print("+++++++++++++++++++++++++++++++++++++++++++++++++++++++")
y=arr.reshape(2,18)
print(y)
print("++++++++++++++++++++++++++++++++++++++++++++++++++++++")
z=arr.reshape(3,12)
print(z)
print("+++++++++++++++++++++++++++++++++++++++++++++++++++++++++")
a=arr.reshape(4,9)
print(a)

36
[[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]
 [13 14 15 16 17 18]
 [19 20 21 22 23 24]
 [25 26 27 28 29 30]
 [31 32 33 34 35 36]]
+++++++++++++++++++++++++++++++++++++++++++++++++++++++
[[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18]
 [19 20 21 22 23 24 25 26 27 28 29 30 31 32 33 34 35 36]]
++++++++++++++++++++++++++++++++++++++++++++++++++++++
[[ 1  2  3  4  5  6  7  8  9 10 11 12]
 [13 14 15 16 17 18 19 20 21 22 23 24]
 [25 26 27 28 29 30 31 32 33 34 35 36]]
+++++++++++++++++++++++++++++++++++++++++++++++++++++++++
[[ 1  2  3  4  5  6  7  8  9]
 [10 11 12 13 14 15 16 17 18]
 [19 20 21 22 23 24 25 26 27]
 [28 29 30 31 32 33 34 35 36]]


In [16]:
#slicing 3D arrays
arr=np.array([[[1,2,3,4,5,6],[7,8,9,10,11,12]],
              [[13,14,15,16,17,18],[19,20,21,22,23,24]],
              [[25,26,27,28,29,30],[31,32,33,34,35,36]]])
print(arr[0,0,1:4])
print("----------")
print(arr[0,0:2,3:5])
print("----------")
print(arr[:,:,:])

[2 3 4]
----------
[[ 4  5]
 [10 11]]
----------
[[[ 1  2  3  4  5  6]
  [ 7  8  9 10 11 12]]

 [[13 14 15 16 17 18]
  [19 20 21 22 23 24]]

 [[25 26 27 28 29 30]
  [31 32 33 34 35 36]]]
